arguments:
  batch_size: 128
  epoch_interval: 5
  epochs: 100
  image_path: train_img
  label_path: label_train.txt
  lr: 0.001
  method: None
  oversampling: 0.1
  training_mode: Val
  undersampling: null
parameters:
  run: log_2024_09_04_19_39_57
performance:
  HTER_train: '0.115755'
  HTER_val: '0.130937'
  f1_train: '0.938562'
  f1_val: '0.934223'
  roc_auc_train: '0.884245'
  roc_auc_val: '0.869063'
