arguments:
  batch_size: 128
  epoch_interval: 5
  epochs: 100
  image_path: train_img
  label_path: label_train.txt
  lr: 0.001
  method: oversampling
  oversampling: 0.5
  training_mode: Val
  undersampling: null
parameters:
  run: log_2024_09_04_22_24_33
performance:
  HTER_train: '0.008888'
  HTER_val: '0.035779'
  f1_train: '0.992412'
  f1_val: '0.968765'
  roc_auc_train: '0.991112'
  roc_auc_val: '0.964221'
