arguments:
  batch_size: 512
  epoch_interval: 5
  epochs: 100
  image_path: train_img
  label_path: label_train.txt
  lr: 0.001
  method: undersampling
  oversampling: null
  training_mode: Val
  undersampling: 0.5
parameters:
  run: log_2024_09_04_09_59_13
performance:
  HTER_train: '0.083073'
  HTER_val: '0.106992'
  f1_train: '0.932595'
  f1_val: '0.917012'
  roc_auc_train: '0.916927'
  roc_auc_val: '0.893008'
